import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header";
import SearchComp from "@/components/search";
import axios from "axios";
import Address from "@/components/fulladd";
import Addresss from "@/components/fulladd1";
import Pagination from "@mui/material/Pagination";
import Stack from "@mui/material/Stack";

function Validators() {
  const router = useRouter();
  const [allData, setAllData] = useState([]);
  const [currentPageData, setCurrentPageData] = useState([]);
  const itemsPerPage = 10;
  const initialPage = parseInt(router.query.page, 10) || 1;
  const [page, setPage] = useState(initialPage);
  const [search, setSearch] = useState(false);

  // useEffect(() => {
  //   const fetchData = async () => {
  //     try {
  //       const response = await axios.get(
  //         "https://myindexer.blockforge.space/validators"
  //       );
  //       setAllData(response.data.result.validators); // Adjust based on actual response structure
  //       console.log(response.data.result.validators);
  //       setCurrentPageData(
  //         response.data.currentValidatorsList.slice(0, itemsPerPage)
  //       );
  //     } catch (error) {
  //       console.error("Failed to fetch data:", error);
  //     }
  //   };
  //   fetchData();
  // }, []);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await axios.get(
          "https://namadaindexer.nodeworld.xyz/validators"
        );
        // Assuming response.data.result.validators is the correct path based on your console.log
        setAllData(response.data.result.validators); // This directly sets allData with the fetched validators array
        // Set the initial page data from the allData state
        setCurrentPageData(
          response.data.result.validators.slice(0, itemsPerPage)
        );
      } catch (error) {
        console.error("Failed to fetch data:", error);
      }
    };
    fetchData();
  }, []);

  const handleChange = (event, value) => {
    const startIndex = (value - 1) * itemsPerPage;
    const endIndex = startIndex + itemsPerPage;
    setCurrentPageData(allData.slice(startIndex, endIndex));
    router.push(
      { pathname: router.pathname, query: { ...router.query, page: value } },
      undefined,
      { shallow: true }
    );
    setPage(value);
  };

  const pageCount = Math.ceil(allData.length / itemsPerPage);

  const myResult = (result) => {
    setSearch(result);
  };

  return (
    <>
      <Head>
        <title>Namada Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.main}>
        <Header />
        <SearchComp myResult={myResult} />
        {!search && (
          <>
            <section className={styles.latestResults_body_trans}>
              <section>
                <section className={styles.latestResults_body_title_trans}>
                  Validators
                </section>
                <table className={styles.latestResults_body_table_trans}>
                  <tbody>
                    {/* Header Row */}
                    <tr
                      className={`${styles.latestResults_body_tr_trans} ${styles.lastTd}`}
                      key="headerRow"
                    >
                      <td className={styles.tdBlock}>
                        <b>Moniker</b>
                      </td>
                      <td className={styles.tdBlock}>
                        <b>Validator Address</b>
                      </td>
                      <td className={styles.tdBlock}>
                        <b>Voting Power</b>
                      </td>
                      <td className={styles.tdBlock}>
                        <b>Opeartor Address</b>
                      </td>
                    </tr>
                    {/* Data Rows */}
                    {currentPageData.map((val, index) => (
                      <tr
                        className={`${styles.latestResults_body_tr_trans} ${
                          index === currentPageData.length - 1
                            ? styles.lastTd
                            : ""
                        }`}
                        key={val.address}
                      >
                        <td className={styles.tdBlock}>
                          <section className={styles.blueText}>
                            #{val.moniker}
                          </section>
                        </td>
                        <td className={styles.tdBlock}>
                          <section className={styles.blueText}>
                            <Address fullAddress={val.address} />
                          </section>
                          <section>
                            <Addresss fullAddress={val.operator_address} />
                          </section>
                        </td>
                        <td className={styles.tdBlock}>
                          <section>
                            <span className={styles.blueText}>
                              {Number(val.voting_power).toLocaleString()}
                            </span>
                          </section>
                        </td>
                        <td className={styles.tdBlock}>
                          <section className={styles.blueText}>
                            <Addresss fullAddress={val.operator_address} />
                          </section>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </section>
            </section>
            <Stack spacing={2} sx={{ bgcolor: "black", p: 2 }}>
              <Pagination
                color="secondary"
                page={page}
                onChange={handleChange}
                count={pageCount}
                sx={{
                  "& .MuiPaginationItem-root": {
                    color: "#fff",
                    borderColor: "rgba(255, 255, 255, 0.23)",
                  },
                }}
              />
            </Stack>
          </>
        )}
      </section>
    </>
  );
}

export default Validators;
