// import React, { useState } from "react";
// import Head from "next/head";
// import styles from "@/styles/Home.module.css";
// import Header from "@/components/header.js";
// import SearchComp from "@/components/search"; // Ensure this path is correct
// import moment from "moment";
// import SearchResults from "@/components/searchResults";

// export default function Search() {
//   const [searchResult, setSearchResult] = useState(null);

//   const handleSearchResult = (result) => {
//     setSearchResult(result);
//   };

//   return (
//     <>
//       <Head>
//         <title>Namada Explorer</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />{" "}
//       </Head>
//       <section className={styles.main}>
//         <Header />
//         <SearchComp onSearchResult={handleSearchResult} />
//         {searchResult && (
//           <section className={styles.searchResults}>
//             <SearchResults results={{ result }} />
//           </section>
//         )}
//       </section>
//     </>
//   );
// }
