import React, { useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "../components/header.js";
import HeroSection from "../components/heroSection.js";
import SearchComp from "../components/search.js";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

export default function Home() {
  const [search, setSearch] = useState(false);

  const myResult = (result) => {
    setSearch(result);
  };

  return (
    <>
      <Head>
        <title>Namada Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../public/favicon" />
      </Head>
      <section className={styles.main}>
        <Header />
        <SearchComp myResult={myResult} />
        {!search && <HeroSection />}
      </section>
    </>
  );
}
