import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header";
import SearchComp from "@/components/search";
import Link from "next/link";
import axios from "axios"; // Assuming you're using axios for API requests

function Click() {
  const [currentPageData, setCurrentPageData] = useState([]); // Data to display on current page
  const router = useRouter();

  // Fetch all data once at component mount
  useEffect(() => {
    const { num } = router.query;
    if (num) {
      const fetchData = async () => {
        try {
          // Use the 'num' query parameter in your API request
          const response = await axios.get(
            `https://namadaindexer.nodeworld.xyz/transactions/${num}`
          );

          // Update state with the API response
          setCurrentPageData(response.data);
        } catch (error) {
          console.error("Failed to fetch data:", error);
        }
      };
      fetchData();
    }
  }, [router.query.num]); // React to changes in 'num' query parameter

  return (
    <>
      <Head>
        <title>Namada Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.main}>
        <Header />
        <SearchComp />
        {/* Render currentPageData here as needed */}
        {/* <BocksTrans data={currentPageData} /> */}
        <section className={styles.latestResults_body_trans}>
          <section>
            <section className={styles.latestResults_body_title_trans}>
              Block Details:
            </section>
            <table className={styles.latestResults_body_table_trans}>
              <tbody>
                {currentPageData.map((data) => {
                  return (
                    <>
                      <tr
                        className={`${styles.latestResults_body_tr_trans} ${
                          0 == 0 - 1 && styles.lastTd
                        }`}
                        key={1025}
                      >
                        <td className={styles.tdBlock}>
                          <section>
                            <b>Block Height:</b>
                          </section>
                          <section className={styles.blueText}>
                            #{data.header_height}
                          </section>
                        </td>
                      </tr>
                      <tr
                        className={`${styles.latestResults_body_tr_trans} ${
                          0 == 0 - 1 && styles.lastTd
                        }`}
                        key={1025}
                      >
                        <td className={styles.tdBlock}>
                          <section>
                            <b>Proposer Address:</b>{" "}
                          </section>
                          <section className={styles.blueText}>
                            {data.header_proposer_address}
                          </section>
                        </td>
                      </tr>
                      <tr
                        className={`${styles.latestResults_body_tr_trans} ${
                          0 == 0 - 1 && styles.lastTd
                        }`}
                        key={1025}
                      >
                        <td className={styles.tdBlock}>
                          <section>
                            <b>Block ID:</b>
                          </section>
                          <section className={styles.blueText}>
                            {data.block_id}
                          </section>
                        </td>
                      </tr>
                      <tr
                        className={`${styles.latestResults_body_tr_trans} ${
                          0 == 0 - 1 && styles.lastTd
                        }`}
                        key={1025}
                      >
                        <td className={styles.tdBlock}>
                          <section>
                            <b>Time:</b>
                          </section>
                          <section className={styles.blueText}>
                            {" "}
                            {new Date(data.header_time).toLocaleString(
                              "en-US",
                              {
                                dateStyle: "medium",
                                timeStyle: "short",
                              }
                            )}
                          </section>
                        </td>
                      </tr>
                      <tr
                        className={`${styles.latestResults_body_tr_trans} ${
                          0 == 0 - 1 && styles.lastTd
                        }`}
                        key={1025}
                      >
                        <td className={styles.tdBlock}>
                          <section>
                            <b>No. of Txs:</b>
                          </section>
                          <section className={styles.blueText}>
                            {data.transaction_count}
                          </section>
                        </td>
                      </tr>
                      <tr
                        className={`${styles.latestResults_body_tr_trans} ${
                          0 == 0 - 1 ? styles.lastTd : ""
                        }`}
                        key={1025}
                      >
                        <td className={styles.tdBlock}>
                          <section>Transaction hashes:</section>
                          {data.transaction_hashes.map((hash, i) => (
                            <section className={styles.blueText}>
                              #{i + 1}:{hash}
                            </section>
                          ))}
                        </td>
                      </tr>
                    </>
                  );
                })}
              </tbody>
            </table>
          </section>
        </section>
      </section>
    </>
  );
}

export default Click;
